### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by danielsf97** [1Password/connect-sdk-go#43]
Hello, 

I'm in the process of integrating 1Password for secret automation in go using this SDK and saw that what I consider one of the best features described in the documentation "LoadStruct" is not yet available through a release. For now I'm referencing this package by a commit hash, but it would be nice if you could create a new release of the sdk.

PS. Keep up the good work, really cool package.

Thanks in advance,
Daniel Fernandes

**Comment by edif2008** [comment]
Hey @danielsf97,

Apologies for the late reply.

I wanted to let you know that we've just released a new version of the Connect Go SDK: v1.3.0.
This release also contains the `LoadStruct` function that you're using.

Thank you for your patience and happy coding 😄
