### ISSUE TITLE
`ContentVersoin` typo

### ISSUE THREAD

**Issue by dustin-ruetz** [1Password/connect-sdk-go#80]
- Location: [`onepassword/vaults.go`](https://github.com/1Password/connect-sdk-go/blob/main/onepassword/vaults.go#L15)
- `Vaults` type
- Typo is `ContentVersoin`; this should say say `ContentVersion`

**Comment by accraw** [comment]
Fixed in https://github.com/1Password/connect-sdk-go/pull/84
